FROM procurement:regional-mapping-v1-c5c5dfcbd091
ARG SOURCE_REVISION
LABEL org.opencontainers.image.revision=$SOURCE_REVISION \
      org.opencontainers.image.base.digest="sha256:70b6be8776cc72930ffe2da100b121febd98dfc582f78f8e3e7eb9ee97f4e0e7" \
      org.opencontainers.image.version="regional-mapping-v2"
USER root
COPY --chown=10001:10001 procurement /app/procurement
USER procurement
