ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG SOURCE_REVISION
ARG BASE_IMAGE_DIGEST
LABEL org.opencontainers.image.revision=$SOURCE_REVISION \
      org.opencontainers.image.base.digest=$BASE_IMAGE_DIGEST \
      org.opencontainers.image.version="procurement-sso-canary-v1"
USER root
COPY --chown=10001:10001 procurement /app/procurement
USER procurement
